#ifndef MANETSIMS_LINKMODEL_CONSTANTS_H
#define MANETSIMS_LINKMODEL_CONSTANTS_H

#ifndef PATHLOSS_CONSTANT_OFFSET
#define PATHLOSS_CONSTANT_OFFSET -18.8
#endif

#ifndef PATHLOSS_EXPONENT
#define PATHLOSS_EXPONENT 5.5
#endif

#ifndef THERMAL_NOISE
#define THERMAL_NOISE -119.66
#endif

#ifndef NOISE_FIGURE
#define NOISE_FIGURE 4.2
#endif

#ifndef STANDARD_DEVIATION
#define STANDARD_DEVIATION 11.4
#endif

#ifndef CORRELATION_COEFFICIENT_THRESHOLD
#define CORRELATION_COEFFICIENT_THRESHOLD 0.01
#endif

#ifndef MAX_LINK_DISTANCE // in km
#define MAX_LINK_DISTANCE 1
#endif

//#define UNDEFINED -0.1


#endif /* MANETSIMS_LINKMODEL_CONSTANTS_H */
